### PR TITLE
Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by croth1** [comment]
Thanks @dpryan79. You may want to add yourself to the recipe-maintainers so that you can merge pull requests in the future 👍 .

**Comment by dpryan79** [comment]
@croth1 Can one just do that by editing the meta.yaml? That seems far to easy.

**Comment by jakirkham** [comment]
How do you mean @dpryan79?

**Comment by croth1** [comment]
@dpryan79, conda-forge is designed in a way that the feedstocks are relatively independent. By adding your name in the maintainer's list and getting merged, you can gain write access in this feedstock yourself. After all conda-forge is a community effort 👍

**Comment by dpryan79** [comment]
@croth1 Cool, I wasn't sure how that worked in conda-forge (I'm more familiar with bioconda). I need to update the recipe anyway to make commonmark a dependency...

**Pull request merged**
