### PR TITLE
Bump to version 0.2.1

### PR DESCRIPTION
**Pull request by dpryan79**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please close and create a branch on your fork and PR from there, @dpryan79. Branches pushed to the main feedstock deploy automatically (even before PR merge).

**Comment by dpryan79** [comment]
@jakirkham Eeek! Really? That's good to know. I presume I need to bump the build number then, correct?

**Comment by jakirkham** [comment]
Yeah. Sorry for the trouble.

We try to list this stuff in the feedstock Readme and the webpage, but it is so commonly missed that we might need to do something else. If you have suggestions of where to put this info where it might be more visible or other actions, please feel free to suggest.

**Comment by dpryan79** [comment]
Wouldn't it be easier to just restrict deployment to post-merge? That's how it works on bioconda.

**Comment by jakirkham** [comment]
We do. However if you push a branch to the main feedstock that will deploy even without a PR. It's like if someone pushed to `master` directly in bioconda. Does that make sense?

**Comment by jakirkham** [comment]
Anyways don't worry about it. Just about everyone has made this mistake including core members (myself included) at least once if not a couple of times. It just points out that things aren't as smooth or obvious as they should be here and we will have to work on a way to improve that somehow.

**Comment by dpryan79** [comment]
Got it, thanks!

**Pull request closed without merging**
