### PR TITLE
Bump to v0.5.0

### PR DESCRIPTION
**Pull request by AA-Turner**
v0.5 dropped support for older versions of Python and also switched to flit. After this is merged I'll make the PRs for 0.5.1 and 0.5.2.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AA-Turner** [comment]
https://github.com/conda-forge/sphinx-argparse-feedstock

**Comment by AA-Turner** [comment]
@conda-forge-admin, please rerender

**Comment by AA-Turner** [comment]
@conda-forge-admin, please rerender

**Comment by croth1** [comment]
LGTM, thanks 👍

**Pull request merged**
